# Generated by Django 5.2.9 on 2026-01-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_remove_ticket_userprofile_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'General'), ('community', 'Community'), ('master', 'Master')], max_length=20),
        ),
    ]
