# Generated by Django 5.2.9 on 2026-01-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_tickettemplate_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='is_actice',
            field=models.BooleanField(default=True),
        ),
    ]
