# Generated by Django 5.2.9 on 2026-01-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_tickettemplate_is_actice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettemplate',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
