# Generated by Django 5.2.9 on 2026-01-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_rename_is_actice_tickettemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'General'), ('community', 'Community'), ('master', 'Master'), ('defunct', 'Defunct')], max_length=20),
        ),
    ]
