# Generated by Django 5.2.9 on 2025-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
