# Generated by Django 5.2.9 on 2026-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0002_remove_payment_amount_remove_payment_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('reserved', 'Reserved'), ('expired', 'Expired')], default='pending', max_length=30),
        ),
    ]
